In [0]:
class SparseMatrix:

    def __init__(self, m, n):
        self.s = [[m, n, 0]]
        self.m = m
        self.n = n
        
    def append(self,i,j,val):
        if val != 0: 
            self.s.append([i,j,val])
        self.s[0][2] = len(self.s) - 1
    
    def shape(self):
        return (self.m, self.n)
    
    def getValue(self, i, j): # (i, j) 의 value를 리턴하는 메소드
        for k in range(1,len(self.s)):
            if self.s[k][0] == i and self.s[k][1] == j:
              return self.s[k][2]
            
#  def getValue(self,i,j):
#      for num in self.s:
#          if num[0] == i and num[1] == j:
#             return num[2] 첫번째 헤더를 포함하므로 불가능
            
    def print(self):
        import numpy as np
        _tmp = np.zeros((self.m, self.n)) # np.zeors 모든 행렬의 원소를 0으로 할당, np.ones 모든 행렬의 원소를 1로 할당
        for i in range(1,len(self.s)):
            _tmp[self.s[i][0]-1,self.s[i][1]-1] = self.s[i][2] # numpy타입은 리스트 안의 리스트 구조가 아니다. 따라서 리스트에서 사용하는 _tmp[self.s[i][0]-1][self.s[i][1]-1] 방식을 이용하지 않고, [X,Y] 방식을 사용하여 값을 호출한다.
        print(_tmp)
        
#  def print(self):
#       import numpy as np
#       _tmp = np.zeros((self.m,self.n))
#        for num in self.s:
#            _tmp[num[0]-1][num[1]-1] = num[2]
#       print(_tmp) 첫 번째 헤드를 포함하므로 불가능

a = SparseMatrix(3,3)
b = SparseMatrix(3,3)

a.append(1,1,1)
a.append(2,2,2)
a.append(3,3,3)
b.append(1,1,4)
b.append(1,2,7)
b.append(2,3,2)
b.append(3,3,1)

a.print()
b.print()

[[1. 0. 0.]
 [0. 2. 0.]
 [0. 0. 3.]]
[[4. 7. 0.]
 [0. 0. 2.]
 [0. 0. 1.]]


In [0]:
def complex(a,b):
  if a.n != b.m:
    return None
  else:
    c = SparseMatrix(a.m, b.n)
    for x in range(1,a.m+1):
      for y in range(1, b.n+1):
        val = 0
        for k in range(1,a.n+1):
          if a.getValue(x,k) != None and b.getValue(k,y) != None:
            val += a.getValue(x,k) * b.getValue(k, y)
        if val != 0:
          c.append(x,y,val)
        
  return c

In [0]:
c = complex(a,b)
c.print()

[[4. 7. 0.]
 [0. 0. 4.]
 [0. 0. 3.]]
