<a href="https://colab.research.google.com/github/YoonSungLee/University-Lectures/blob/master/DataStructure/%EA%B3%B5%EB%B6%80%EC%9E%90%EB%A3%8C)_Ch_2_LinkedList.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# 각 변수를 이용
a1 = 1
a2 = 2
a3 = 3
sum = a1 + a2 + a3
sum

6

In [0]:
# 배열(Array)을 이용
a = [1,2,3]
sum = 0
for i in range(3):
  sum += a[i]
sum

6

# <font color='blue'><div style="text-align: center">Ch 2. Linked List</font> 

* 아래 그림 처럼 노드를 연결시킨 자료구조
* 자료를 연속적인 메모리 공간에 할당할 필요없이 임의 공간에 자료를 저장하고 링크를 이용해 연결함
* 리스트에서 원소를 탐색하기 위해서는 순차탐색을 하여야 함 ex) '배'를 찾기 위해 사과 ,앵두, 배 순으로 순차탐색 필요
* 배열에서는 삽입/삭제 시 원소 이동이 필요한데 반해 리스트에서는 삽입/삭제가 원활함
* 리스트 이름 S에는 사과 노드의 주소가 저장됨
* 사과노드는 과일을 저장할 수 있는 장소와 다음 노드의 주소를 저장하는 장소로 구성됨
* 마지막 노드의 링크는 null 이 저장됨
* 단점 : 공간이 많이 필요하고 속도가 느리다 but 공간과 속도의 지속적인 개선으로 Linked List 사용
* 일반적으로는 배열이 더 우수한 성능을 보인다. 하지만 특정한 상황에서는 LinkedList가 더 효율적이다.
<center> ![](https://drive.google.com/uc?id=1hgU-79vThtZWe_0wWB0ZTGHmgmPtE020) </center>
        

In [0]:
# 클래스 구조
class Student: # 클래스 이름은 대문자로 시작
  def __init__(self,0): # 생성자(__init__)
    """내용"""

In [0]:
# Node Class: item으로 value를 가지고 link를 가진다. link가 없을 경우, None을 입력한다.
class Node:
    def __init__(self, item=None):
        self.item = item
        self.link = None

a = Node('사과') # self 에 a, item에 '사과' 대입
print(id(a))
print(a.item)
print(a.link)

139745549212528
사과
None


* Linked List 설계
 * root: 리스트 루트 노드이고 Linked List는 root 노드의 주소를 가진다.
   * root = Node() # 빈 노드(리스트)를 하나 생성한다. 즉,  item = None
 * append method: item을 주면 item 노드를 Linked List 마지막 노드에 추가하는 메소드
   * item으로 newNode를 만들고 root의 item이 None이면 newNode를 root로 지정하고 아니면 리스트의 끝까지 이동한 후, 마지막 노드의 링크에 newNode의 주소를 삽입
 * insert method: Linked List에 index로 새 노드를 추가하는 메소드로 index=0 이면 root로 추가하고, index 값에 따라 해당 위치에 삽입한다.
   * index < 0 or index >= listSize 이면 error 메세지를 출력한다.
   * rootNode를 0번째로 보고 index -1 번째 노드의 링크에 newNode를 넣고 newNode의 링크에      index-1 번째 링크에 있던 주소를 넣는다.
 * find Method: Linked List에서 해당 아이템을 찾고 index를 리턴한다.  없으면 -1을 리턴한다.
 * delete method: 주어진 값을 이용해 해당 노드를 찾고 지운다.
   * curNode = preNode = root로 초기 지정하고 curNode를 움직일 때 마다 preNode는 curNode의 이전 노드로 갱신한다
   * del item이 첫번째 노드면 self.root에 del item의 링크를 넣는다.
   * del item이 중간노드면preNode 링크에 del item 링크를 넣는다.
   *  마지막 노드라면 preNode 링크에 None를 넣는다.
 
 * listSize method: Linked List의 item 수를 리턴한다.

 * print method: Linked List를 print 한다.

 

In [0]:
# root 노드 만들기

class LinkedList:
    def __init__(self):
        self.root = Node()

fruits = LinkedList()


In [0]:
# append 메소드 구현

class LinkedList:
    def __init__(self):
        self.root = Node()

    def append(self, item):
        newNode = Node(item)
        curNode = self.root
        if curNode.item == None:
            self.root = newNode
        else:
            while curNode.link != None:
                curNode = curNode.link
            curNode.link = newNode
    
    def print(self):
        curNode = self.root
        print(curNode.item)
        while curNode.link != None:
            curNode = curNode.link
            print(curNode.item)

fruits = LinkedList()
fruits.append('사과')
fruits.print()
fruits.append('앵두')
fruits.append('오렌지')
fruits.append('포도')
fruits.print()

사과
사과
앵두
오렌지
포도


In [0]:
# insert 메소드 구현
class LinkedList:
    def __init__(self):
        self.root = Node()

    def append(self, item):
        newNode = Node(item)
        curNode = self.root
        if curNode.item == None:
            self.root = newNode
        else:
            while curNode.link != None:
                curNode = curNode.link
            curNode.link = newNode
    
    def print(self):
        curNode = self.root
        print(curNode.item)
        while curNode.link != None:
            curNode = curNode.link
            print(curNode.item)
    
    def listSize(self):
        curNode = self.root
        cnt = 1
        while curNode.link != None:
            curNode = curNode.link
            cnt += 1
        return cnt
            
    def insert(self, idx, item):
        n = self.listSize()
        if idx < 0 or idx >= n:
            print("index range error")
        else:
            newNode = Node(item)
            curNode = self.root
            if idx == 0:
                _tmp = self.root
                self.root = newNode
                newNode.link = _tmp
            else:
                for curIdx in range(idx-1):
                    curNode = curNode.link
                _tmp = curNode.link
                curNode.link = newNode
                newNode.link = _tmp

fruits = LinkedList()
fruits.append('사과')
fruits.append('앵두')
fruits.append('오렌지')
fruits.append('포도')
fruits.insert(3,'배')   
fruits.print()
            
            

사과
앵두
오렌지
배
포도


In [0]:
# find 메소드 구현
class LinkedList:
    def __init__(self):
        self.root = Node()

    def append(self, item):
        newNode = Node(item)
        curNode = self.root
        if curNode.item == None:
            self.root = newNode
        else:
            while curNode.link != None:
                curNode = curNode.link
            curNode.link = newNode
    
    def print(self):
        curNode = self.root
        print(curNode.item)
        while curNode.link != None:
            curNode = curNode.link
            print(curNode.item)
    
    def listSize(self):
        curNode = self.root
        cnt = 1
        while curNode.link != None:
            curNode = curNode.link
            cnt += 1
        return cnt
            
    def insert(self, idx, item):
        n = self.listSize()
        if idx < 0 or idx >= n:
            print("index range error")
        else:
            newNode = Node(item)
            curNode = self.root
            if idx == 0:
                _tmp = self.root
                self.root = newNode
                newNode.link = _tmp
            else:
                for curIdx in range(idx-1):
                    curNode = curNode.link
                _tmp = curNode.link
                curNode.link = newNode
                newNode.link = _tmp
    
    def find(self, item):
        find = -1
        idx = 0
        if self.root.item == item:
            find += 1
        else:
            curNode = self.root
            while curNode.link != None:
                curNode = curNode.link
                idx += 1
                if curNode.item == item:
                    find = idx
                    break
        return find
        

fruits = LinkedList()
fruits.append('사과')
fruits.append('앵두')
fruits.append('오렌지')
fruits.append('포도')
fruits.insert(3,'배')   
fruits.find('배~')

-1

In [0]:
# 구현 후에는 항상 노드의 처음, 중간, 끝을 확인할 것

In [0]:
# delete 메소드 구현
# find method를 이용해 delete 할 item의 인덱스를 구한다.
# del item이 첫번째 노드면 self.root에 del item의 링크를 넣는다.
# del item이 중간노드면 index-1 번째 링크에 del item 링크를 넣는다.
# 마지막 노드라면 index-1 번째 링크에 None를 넣는다.

class LinkedList:
    def __init__(self):
        self.root = Node()

    def append(self, item):
        newNode = Node(item)
        curNode = self.root
        if curNode.item == None:
            self.root = newNode
        else:
            while curNode.link != None:
                curNode = curNode.link
            curNode.link = newNode
    
    def print(self):
        curNode = self.root
        print(curNode.item)
        while curNode.link != None:
            curNode = curNode.link
            print(curNode.item)
    
    def listSize(self):
        curNode = self.root
        cnt = 1
        while curNode.link != None:
            curNode = curNode.link
            cnt += 1
        return cnt
            
    def insert(self, idx, item):
        n = self.listSize()
        if idx < 0 or idx >= n:
            print("index range error")
        else:
            newNode = Node(item)
            curNode = self.root
            if idx == 0:
                _tmp = self.root
                self.root = newNode
                newNode.link = _tmp
            else:
                for curIdx in range(idx-1):
                    curNode = curNode.link
                _tmp = curNode.link
                curNode.link = newNode
                newNode.link = _tmp
    
    def find(self, item):
        find = -1 # find를 정의하는 이유?
        idx = 0
        if self.root.item == item:
            find += 1
        else:
            curNode = self.root
            while curNode.link != None:
                curNode = curNode.link
                idx += 1
                if curNode.item == item:
                    find = idx
                    break
        return find
    
#     def find(self, item):
#         answer = 0
#         if self.root.item == item:
#                 return answer
#         else:
#             curNode = self.root
#             while curNode.link != None:
#                 curNode = curNode.link
#                 answer += 1
#                 if curNode.item == item:
#                     return answer
#             return -1
    
    
    def delete(self,item):
        delYN = False
        curNode = self.root
        preNode = curNode
        if curNode.item == item:
            self.root = self.root.link
            delYN = True
        else:
            while curNode.link != None:
                preNode = curNode
                curNode = curNode.link
                if curNode.item == item:
                    preNode.link = curNode.link
                    delYN = True
        if curNode.item == item:
            preNode.link = None
            delYN = True
        if delYN == False:
            print("delete failed")
            
    def remove(self, item): #delete의 다른 표현법
      curNode = self.root
      preNode = self.root
      if self.root.item == item:
        self.root = self.root.link
      else:
        while curNode != None:
          if curNode.item == item:
            preNode.link = curNode.link
            break
          preNode = curNode
          curNode = curNode.link

            
# "while curNode.link != None" 의 전에 (실행) 과정이 있어야 한다.
# "while curNode.link != None" 을 이후로 (노드 바꾸기) -> (실행) 과정을 거치는 코드를 작성해야 한다.

#     def remove(self, item):
#         if self.root.item == item:
#             self.root = self.root.link
#         else:
#             curNode = self.root
#             preNode = self.root
#             while curNode.link != None:
#                 preNode = curNode
#                 curNode = curNode.link
#                 if curNode.item == item:
#                     preNode.link = curNode.link
#                     return
#             return "No item"


        
fruits = LinkedList()
fruits.append('사과')
fruits.append('앵두')
fruits.append('오렌지')
fruits.append('포도')
 
fruits.delete('포도~')
fruits.print()

delete failed
사과
앵두
오렌지
포도


<font color='red'> <H.W # 1> Linked List class를 위 코드를 보지 말고 스스로 작성해 보세요.</font>

#### 리스트 응용문제: 다항식 덧셈

* $ p(x) = 4 x^4 + 3x^2 + 3$ , $ q(x) = 3 x^3 + 4x^2 +2x + 1$ 를 더하면 
$ p(x) + q(x) = 4x^4 + 3 x^3 + 7 x^2 + 2x + 4 $ 가 된다.
* 이 연산을 수행하는 프로그램을 만들어 보자.
    * 다항식 p(x) 를 저장하는 자료구조: [[4,4], [3,2], [3,0]]
    * add method: 리스트 자료구조에 [coef, k] 형식의 서브 리스트를 추가한다.
    * peek method: 0번째 리스트 원소를 리턴한다.
    * pop method: 0번째 리스트 원소를 꺼내 리턴한다.
    * size method: 리스트의 길이를 리턴한다.
    * print method: 다항식 형태를 프린트 한다.

In [0]:
# 이것만으로는 LinkedList의 예시라고 할 수 없다.

class Poly:
    def __init__(self):
        self.eq = []
    def add(self, coef, k):
        self.eq.append([coef, k])
    def peek(self):
        return self.eq[0]
    def pop(self):
        return self.eq.pop(0)
    def size(self):
        return len(self.eq)
    def print(self):
        for term in self.eq:
            print(term[0],'x^',term[1],'+', end=' ')
        print()
        
p = Poly()
p.add(4,4)
p.add(3,2)
p.add(3,0)

q = Poly()
q.add(3,3)
q.add(4,2)
q.add(2,1)
q.add(1,0)

p.print()
q.print()

# print(p.peek())
# print(q.peek())

# print(p.pop())
# print(q.pop())

# p.print()
# q.print()

4 x^ 4 + 3 x^ 2 + 3 x^ 0 + 
3 x^ 3 + 4 x^ 2 + 2 x^ 1 + 1 x^ 0 + 


####  다항식 덧셈 알고리즘

* Step 0: 덧셈 결과를 기록할 빈 다항식을 만든다.
* Step 1: 두개의 다항식에서 최고 차수를 찾고 최고 차수가 있는 리스트에서 팝하여 결과 다항식에 추가한다. 만약, 최고 차수를 가지는 항이 두개 다항식에 공통으로 존재하면 계수를 합하여 add한다.
* Step 2: 한쪽 다항식이 empty 할 때까지 Step 1을 수행한다.
* Step 3: 비어 있지 않은 다항식의 항을 결과 다항식에 add 한다.

In [0]:
# 리스트에서 최고차수를 가진 리스트의 인덱스번호가 가장 낮다고 가정한다.

def polyAdd(a,b):
    c = Poly()
    while a.size() > 0 and b.size() > 0: # a와 b 둘다 남아있을 때
        if a.peek()[1] > b.peek()[1]:
            _tmp = a.pop()
            c.add(_tmp[0], _tmp[1])
        elif a.peek()[1] < b.peek()[1]:  
            _tmp = b.pop()
            c.add(_tmp[0], _tmp[1])
        else:
            _tmp1 = a.pop()
            _tmp2 = b.pop()
            c.add(_tmp1[0]+_tmp2[0], _tmp1[1])
    
    while a.size() > 0: # a만 남아있을 때
        _tmp = a.pop()
        c.add(_tmp[0],_tmp[1])

    while b.size() > 0:# b만 남아있을 때
        _tmp = b.pop()
        c.add(_tmp[0],_tmp[1])
    
    return c

c = polyAdd(p, q)
c.print()

# Array를 사용하지 않는 이유 : 다항식에 모든 차수가 있지 않게 되면 빈 차수를 모두 0으로 가지고 있어야 한다.(효율성이 떨어진다)

4 x^ 4 + 3 x^ 3 + 7 x^ 2 + 2 x^ 1 + 4 x^ 0 + 


#### 리스트 응용문제: 희소행렬
* 희소행렬은 행렬 원소에 0이 많이 포함된 행렬을 말한다.
* 희소행렬을 저장할 때, 0도 값이기 때문에 메모리를 차지한다.
* Term-Document Matrix가 대표적인 희소행렬이다.

 <center>![그래프](https://drive.google.com/uc?id=1FnZFSrbvGwieHL4wr6G91hEfZX682XbR)</center>
 * D1에 각 단어의 빈도수를 저장한다.(D1만으로도 이 문서의 주제 추론 가능)
* 희소행렬을 효율적으로 저장하기 위해 아래와 같은 자료구조를 생각할 수 있다.
 <center>![그래프](https://drive.google.com/uc?id=1ts4fkwXuu_0MiRP-oMCH17Y9eLl79NQp)</center>
* (x좌표, y좌표, 값)의 구조로 자료구조를 구성할 수 있다.(LinkedList)
* 0 번째 행에는 행렬의 차원 m, n, non-zero element 수를 추가한다.(헤더)
* m = 8, n = 7, non_zero elemnet = 10 (헤더)

* SparseMatrix 자료구조
  * 행렬의 dimension m, n 을 입력받아 희소행렬 리스트를 [[m,n,0]]로 초기 설정한다. 이때 m,n은 index가 아니라 행과 열의 수를 의미한다.
  * append method: [i, j, value] 형태의 리스트를 희소행렬 리스트에 추가한다.( 단, value != 0일때) 이때 i,j는 index가 아니라 행과 열을 의미한다.
  * shape method: 희소행렬 dimension을 리턴한다.
  * getValue method: i, j 행렬값을 리턴한다.
  * print method: 희소행렬을 일반적 행렬 형태로 프린트한다. (0으로 구성된 m,n array를 만들고 i,j 행렬값을 업데이트한다.)

In [0]:
class SparseMatrix:

    def __init__(self, m, n):
        self.s = [[m, n, 0]]
        self.m = m
        self.n = n
        
    def append(self,i,j,val):
        if val != 0: 
            self.s.append([i,j,val])
        self.s[0][2] = len(self.s) - 1
    
    def shape(self):
        return (self.m, self.n)
    
    def getValue(self, i, j): # (i, j) 의 value를 리턴하는 메소드
        for k in range(1,len(self.s)):
            if self.s[k][0] == i and self.s[k][1] == j:
              return self.s[k][2]
            
#  def getValue(self,i,j):
#      for num in self.s[1:]:
#          if num[0] == i and num[1] == j:


# numpy타입은 리스트 안의 리스트 구조가 아니다.
# 따라서 리스트에서 사용하는 _tmp[self.s[i][0]-1][self.s[i][1]-1] 방식을 이용하지 않고,
# [X,Y] 방식을 사용하여 값을 호출한다.
# 또한 numpy타입에서 값을 호출할 때에는 index 개념을 이용하여야 한다.(-1을 해주는 이유)
    def print(self):
        import numpy as np
        _tmp = np.zeros((self.m, self.n)) # np.zeors 모든 행렬의 원소를 0으로 할당, np.ones 모든 행렬의 원소를 1로 할당
        for i in range(1,len(self.s)):
            _tmp[self.s[i][0]-1,self.s[i][1]-1] = self.s[i][2]
        print(_tmp)
        
#  def print(self):
#       import numpy as np
#       _tmp = np.zeros((self.m,self.n))
#        for num in self.s[1:]:
#            _tmp[num[0]-1][num[1]-1] = num[2]

a = SparseMatrix(3,3)
b = SparseMatrix(3,3)

a.append(1,1,1)
a.append(2,2,2)
a.append(3,3,3)
b.append(1,1,4)
b.append(1,2,7)
b.append(2,3,2)
b.append(3,3,1)

a.print()
b.print()

print(a.getValue(3,3))
                
        

[[1. 0. 0.]
 [0. 2. 0.]
 [0. 0. 3.]]
[[4. 7. 0.]
 [0. 0. 2.]
 [0. 0. 1.]]
3


* 희소행렬의 전치행렬 알고리즘 : 희소행렬의 행 [i,j,val] 을 [j, i, val] 로 바꿔 리턴한다.

* 두 희소행렬의 덧셈 알고리즘: 
  * 덧셈 결과를 저장할 빈 희소행렬 c를 만든다.
  * 두 희소행렬 a, b의 unique 한 (i,j) 쌍의 집합을 u 라고 하자.
  * u에서 원소를 하나씩 꺼내면서 a, b의 해당 위치 값을 구해 더한다.
  * 위에서 구한 값이 0이 아니면 c에 추가한다.


In [0]:
def transpose(a):
    t_a = SparseMatrix(a.n,a.m)
    
    for i in range(len(a.s)):
        if i == 0:
            t_a.s[0][2] = a.s[0][2]
        else:
            t_a.append(a.s[i][1],a.s[i][0],a.s[i][2])

    return t_a

t_b = transpose(b)
t_b.print()
        

[[4. 0. 0.]
 [7. 0. 0.]
 [0. 2. 1.]]


In [0]:
def add(a, b):
    if a.shape() != b.shape():
        print("두 행렬의 차원이 달라 더할 수 없습니다.")
    else:
        c = SparseMatrix(a.shape()[0], a.shape()[1])
        u = set() # 집합의 중복을 허용하지 않는 특성 이용
        for i in range(1,len(a.s)):
            u.add((a.s[i][0], a.s[i][1]))
        for i in range(1,len(b.s)):
            u.add((b.s[i][0], b.s[i][1]))
        for item in u:
            _tmp = a.getValue(item[0], item[1]) + b.getValue(item[0], item[1])
            if _tmp != 0:
                c.append(item[0], item[1], _tmp) 
    return c

a.print()
b.print()
c = add(a, b)
c.print()

[[1. 0. 0.]
 [0. 2. 0.]
 [0. 0. 3.]]
[[4. 7. 0.]
 [0. 0. 2.]
 [0. 0. 1.]]
[[5. 7. 0.]
 [0. 2. 2.]
 [0. 0. 4.]]


<font color='red'>H.W # 2: 두 희소 행렬의 곱셈을 수행하는 함수를 작성하시오. </font>

$$ C_{ij} = \sum_k A_{ik} \cdot B_{kj} $$

1. 두 행렬의 곱셈은 A는 r by c, B는 c by l 과 같이 A의 열의 수와 B의 행수가 같아야 한다.         아니면 null을 리턴한다. 곱셈 결과 C 행렬은 r by l이 된다.
2. 희소행렬 곱셈 결과를 저장할 빈 리스트를 생성한다. 
3.  위의 식 $ C_{ij} $ 를 계산해서 그 값이 0 이 아니면 C 희소행렬에 (i,j, 계산값)을 추가한다.   
4. C 희소행렬에  add 한 개수와 결과 dimension을 계산한 후, 헤더를 업데이트 한다.
5. C 희소행렬을 반환한다.


In [0]:
# SparseMatrix의 곱으로 SparseMatrix 결과 출력
# 희소행렬의 원소 개수는 (전체 원소 개수) - 1

In [0]:
# H.W 2

def complex(a,b):
  if a.n != b.m:
    return None
  else:
    c = SparseMatrix(a.m, b.n)
    for x in range(1,a.m+1):
      for y in range(1, b.n+1):
        val = 0
        for k in range(1,a.n+1):
          if a.getValue(x,k) != None and b.getValue(k,y) != None:
            val += a.getValue(x,k) * b.getValue(k, y)
        if val != 0:
          c.append(x,y,val)
        
  return c

In [0]:
def mult(a,b):
  if a.shape()[1] != b.shape()[0]:
    print("Dimension Error")
  else:
    m = a.shape()[0]
    n = b.shape()[1]
    l = a.shape()[1]
    # a.m, a.n 대신 method를 통해서 구현하는 습관 필요(a.m, a.n과 같은 방법은 설계자만이 알고 있는 방법, 은닉 필요)
    
    c = SparseMatrix(m,n)
    for i in range(1, m+1):
      for j in range(1, n+1):
        _sum = 0
        for k in range(1, l+1):
          _sum += a.getValue(i,k)*b.getValue(k,j) #getValue에서 못찾으면 return 0 수정 필요
        if _sum != 0:
          c.append(i,j,_sum)
  return c
  
mult(a,b)

In [0]:
# 문제의 4번 조건을 코드로 작성(X)? >>> SparseMatrix의 append 메소드가 원소를 추가시킬때마다 헤더를 업데이트한다.

### Double Linked List

* Double Linked List는 아래 그림처럼 링크가 좌, 우에 두개가 존재하는 Linked List다.
* Single Linked List는 삭제를 위해서 preNode를 관리해야 하는 불편함이 있는데 Double Linked List는 preNode를 알 수 있는 장점은 있지만 이를 위해 링크를 두 개 관리해야 하는 손실이 있다.

<center> ![](https://drive.google.com/uc?id=1STHXAzEkDwb0ailRcZuRNKU_TGYI3RJK) </center>
        
* Double Linked List 설계

 * DNode: item과 left, right에 각각 좌, 우 노드의 주소를 저장한다.
 
 * root: 리스트 루트 노드이고 Double Linked List는 root 노드의 주소를 가진다.
    * root = DNode()
    
  * append method: item을 주면 item을 가진 새 노드를 Linked List 마지막 노드에 추가하는 메소드
   * newNode를 만들고 root의 item이 None이면 newNode를 root로 지정하고 아니면 리스트의 끝까지 이동한 후, 마지막 노드의 right에 newNode의 주소를 삽입하고 newNode의 left에 마지막 노드의 주소를 삽입한다.

 * insert method: Linked List에 index로 새 노드를 추가하는 메소드로 index=0 이면 root로 추가하고, index 값에 따라 해당 위치에 삽입한다.
   * index < 0 or index >= listSize 이면 error 메세지를 출력한다.
   * rootNode를 0번째로 보고 index -1 번째 노드 주소를 newNode의 left에 넣고, index번째 노드의 주소를 newNode right에 넣는다.
   
 * find Method: Linked List에서 해당 아이템을 찾고 index를 리턴한다.  없으면 -1을 리턴한다.
 
 * delete method: 주어진 값을 이용해 해당 노드를 찾고 지운다.
   * del item이 첫번째 노드면 self.root에 self.root.right를 넣고 self.root.left에 None를 넣는다.
   * del item이 중간노드면 delNode.left.right에 delNode.right를 삽입한다.
   * 마지막 노드라면 마지막 노드 left.right에 None를 삽입한다.
 
 * listSize method: Linked List의 item 수를 리턴한다.

 * print method: Linked List를 print 한다.

In [0]:
# Node Class: item으로 value를 가지고 right, left를 가진다. link가 없을 경우, None을 입력한다.
class DNode:
    def __init__(self, item=None):
        self.item = item
        self.right = None
        self.left = None

a = DNode('사과')
print(id(a))

139647214791984


H.W # 3: Double Linked List 클래스를 작성하시오.

In [0]:
class DNode:
    def __init__(self, item = None):
        self.item = item
        self.right = None
        self.left = None

class DoubleLinkedList:
    def __init__(self):
        self.root = DNode()
        
    def append(self,item):
        newNode = DNode(item)
        if self.root.item == None:
            self.root = newNode
        else:
            curNode = self.root
            while curNode.right != None:
                curNode = curNode.right
            curNode.right = newNode
            newNode.left = curNode
            
    def print(self):
        curNode = self.root
        print(self.root.item)
        while curNode.right != None:
            curNode = curNode.right
            print(curNode.item)
            
    def listSize(self):
        curNode = self.root
        cnt = 1
        while curNode.right != None:
            curNode = curNode.right
            cnt += 1
        return cnt
    
    def insert(self,idx,item):
        n = self.listSize()
        if (idx < 0 ) or (idx >= n ):
            print("ERROR")
        else:
            newNode = DNode(item)
            curNode = self.root
            if idx == 0:
                _tmp = self.root
                self.root = newNode
                newNode.right = _tmp
                _tmp.left = newNode
            else:
                for i in range(idx - 1):
                    curNode = curNode.right
                _tmp = curNode.right
                curNode.right = newNode
                newNode.left = curNode
                newNode.right = _tmp
                _tmp.left = newNode
                
    def find(self,item):
        find = -1
        idx = 0
        if self.root.item == item:
            find += 1
        else:
            curNode = self.root
            while curNode.right != None:
                curNode = curNode.right
                idx += 1
                if curNode.item == item:
                    find = idx
                    break
        return find
    
#     def find(self,item):
#         idx = 0
#         curNode = self.root
#         while curNode.right != None:
#             if curNode.item != item:
#                 curNode = curNode.right
#                 idx += 1
#             elif curNode.item == item:
#                 return idx
#         return -1

#     def find(self,item):
#         cnt = 0
#         if self.root.item == item:
#             return cnt
#         else:
#             curNode = self.root
#             while curNode.right != None:
#                 curNode = curNode.right
#                 cnt += 1
#                 if curNode.item == item:
#                     return cnt
#             return -1
    
    def delete(self,item):
        if self.root.item == item:
            self.root = self.root.right
            self.root.left = None
            return None
        else:
            curNode = self.root
            while curNode.right != None:
                curNode = curNode.right
                if curNode.item == item:
                    if curNode.right == None:
                        curNode.left.right = None
                    else:
                        curNode.left.right = curNode.right
                        curNode.right.left = curNode.left
                    return None
        print("대상 item이 리스트 안에 없습니다.")

### Circle Linked List

* Circle Linked List는 아래 그림처럼 마지막 노드의 링크에 root 노드의 주소를 삽입한 것이다.
* Single Linked List의 약점(되돌아갈 수 없다) 보완, Double Linked List의 약점(메모리의 사용이 많다) 보완한 구조
* Single Linked List는 항상 root로 부터 순차탐색을 해야 하는데 Circle Linked List는 아무 위치에서나 원형으로 탐색이 가능하다.
* 무한반복 mp3, 혹은 사진 슬라이드 쇼 플레이 순서를 만드는 예와 같이 순서가 계속 반복되는 원형 자료구조에 적합하다.

<center> ![](https://drive.google.com/uc?id=17AbC2e28EEN8f7RTQUl4uUbgn5ueAeUb) </center>

* Circle Linked List 설계
 * root: 리스트 루트 노드이고 Linked List는 root 노드의 주소를 가진다.   root = Node()
 * tail : 리스트 마지막 노드이고 tail.link = root 가 된다. 마지막 노드를 관리하는 이유는 루트가 삭제될 경우, tail.link를 갱신해야 하기 때문이다.
 * current: 리스트 순환을 위해 현재 노드를 관리한다. 
 * print method : 모든 item을 보여준다. 
 * append method: item을 주면 item 노드를 tail 노드 다음에 추가하는 메소드
   * newNode를 만들고 root의 item이 None이면 newNode를 root와 tail로 지정하고 newNode 링크에 root 주소를 삽입한다.  아니면 tail 링크에 newNode의 주소를 삽입하고 newNode 링크에는 root 주소를 삽입한다. 이후, newNode를 tail로 갱신한다.

 * setCurrent method: 리스트에서 item을 가지는 노드를 current 노드로 지정한다.
 * moveNext method: current 노드를 다음 노드로 이동시킨다.
  * insert method: current 노드 다음에 새노드를 삽입한다.
   * current 노드 링크에 새 노드를 지정하고 새노드의 링크에 current 노드에 연결되어 있던 링크를 지정하여 연결한다.
   * 만약, current가 tail 노드 였다면 새노드를 tail 노드로 재지정한다.

 * delete method: 주어진 값을 이용해 해당 노드를 찾고 지운다.
   * curNode = preNode = root로 초기 지정하고 curNode를 움직일 때 마다 preNode는 curNode의 이전 노드로 갱신한다.
   * del item이 첫번째 노드면 root에 del item의 링크를 넣고 tail노드의 링크에 값을 root로 갱신한다. 
   * del item이 중간노드면 preNode 링크에 del item의 링크를 넣는다.
   *  마지막 노드라면 preNode 링크에 del item의 링크를 넣고 tail 노드를 preNode로 갱신한다.

In [0]:
class Node:
    def __init__(self, item=None):
        self.item = item
        self.link = None
        
class CircleLinkedList:
    def __init__(self):
        self.root = Node()
        self.tail = self.root
        self.current = self.root
        
    def append(self, item):
        # 추가할 새노드를 만든다.
        newNode = Node(item)
        # 루트가 비어 있으면 루트와 테일을 새노드로 지정한다.
        if self.root.item == None:
            self.root = newNode
            self.tail = newNode
            newNode.link = self.root
        else:
        # 루트가 비어 있지 않으면 테일 뒤에 새노드를 추가하고 테일을 업데이트한다.
            _tmp = self.tail.link
            self.tail.link = newNode
            newNode.link = _tmp # self.tail.link == self.root이므로 _tmp를 이용하지 않고 newNode.link = self.root으로 구현 가능
            self.tail = newNode
#       else:
#           self.tail.link = newNode
#           newNode.link = self.root
#           self.tail = newNode
            

    # 리스트 안에 모든 노드를 프린트 한다. 
    def print(self):
        curNode = self.root
        print(curNode.item)
        while curNode.link != self.root: # Single Linked List와의 가장 큰 차이
            curNode = curNode.link
            print(curNode.item)

    # 리스트에 존재하는 노드 수를 구한다.
    def listSize(self):
        curNode = self.root
        cnt = 1
        while curNode.link != self.root:
            curNode = curNode.link
            cnt += 1
        return cnt

    # 리스트에서 item을 가지는 노드를 current 노드로 지정한다.
    def setCurrent(self,item):
        curNode = self.root
        for i in range(self.listSize()):
            if curNode.item == item:
                self.current = curNode
            else:
                curNode = curNode.link
#     def setCurrent(self,item):
#         curNode = self.root
#         while curNode.item != item:
#             curNode = curNode.link
#         self.current = curNode

#     def setCurrent(self,item):
#         if self.root.item == item:
#             self.current = self.root
#         else:
#             curNode = self.root
#             while curNode.link != self.root:
#                 curNode = curNode.link
#                 if curNode.item == item:
#                     self.current = curNode
#                     return
#             return "set failed"
                

    # current 노드를 다음 노드로 바꾼다.(바뀐 노드의 아이템 출력)
    def moveNext(self):
        self.current = self.current.link
        print("현재 위치는 ", self.current.item, "입니다.")

    # current 다음에 item을 삽입한다.
    def insert(self, item):
        # 삽입할 새 노드를 만든다.
        newNode = Node(item)
        # current 노드의 링크에 새 노드를 지정하고 새노드의 링크에 current 노드가 연결되어 있던 링크를 지정하여 연결한다.
        _tmp = self.current.link
        self.current.link = newNode
        newNode.link = _tmp
        # 만약, item1이 tail 노드 였다면 새노드를 tail 노드로 재지정한다.
        if self.current == self.tail:
            self.tail = newNode

    # item을 가지는 노드를 삭제한다.
    def delete(self, item):
        delYN = False
        # 루트가 삭제 대상 노드인지 확인한다. 루트를 삭제할 경우, 루트 다음 노드를 루트로 갱신하고 tail 노드의 링크를 갱신된 루트로 재지정한다.
        curNode = self.root
        if curNode.item == item:
            self.root = self.root.link
            self.tail.link = self.root
            delYN = True
        # 루트가 삭제 대상이 아닐 경우, 끝까지 탐색하면서 item이 존재하는 노드를 찾는다.
        # 찾았다면 preNode의 링크에 대상노드 링크를 넘겨준다. 만약, 대상 노드가 tail노드라면 tail 노드를 preNode로 변경한다.
        else:
            while curNode.link != self.root:
                preNode = curNode
                curNode = curNode.link
                if curNode.item == item:
                    preNode.link = curNode.link
                    if curNode == self.tail:
                        self.tail = preNode
                    delYN = True
        # 삭제를 하지 못했으면 error message를 출력한다.
        if delYN == False: print("delete failed")
            
#     def delete(self,item):
#         if self.root.item == item:
#             self.root = self.root.link
#             self.tail.link = self.root
#         else:
#             curNode = self.root
#             preNode = self.root
#             while curNode.link != self.root:
#                 preNode = curNode
#                 curNode = curNode.link
#                 if curNode.item == item:
#                     preNode.link = curNode.link
#                     if curNode == self.tail:
#                         self.tail = preNode
#                     return
#             return "delete failed"

fruits = CircleLinkedList()
fruits.append('사과')
fruits.append('앵두')
fruits.append('오렌지')
fruits.append('포도')

fruits.print()
print(fruits.listSize())
fruits.setCurrent("포도")
fruits.insert("수박")
print(fruits.tail.item)

fruits.setCurrent('오렌지')
for i in range(10):
    fruits.moveNext()

fruits.delete('포도')
fruits.setCurrent('오렌지')
for i in range(10):
    fruits.moveNext()

사과
앵두
오렌지
포도
4
수박
현재 위치는  포도 입니다.
현재 위치는  수박 입니다.
현재 위치는  사과 입니다.
현재 위치는  앵두 입니다.
현재 위치는  오렌지 입니다.
현재 위치는  포도 입니다.
현재 위치는  수박 입니다.
현재 위치는  사과 입니다.
현재 위치는  앵두 입니다.
현재 위치는  오렌지 입니다.
현재 위치는  수박 입니다.
현재 위치는  사과 입니다.
현재 위치는  앵두 입니다.
현재 위치는  오렌지 입니다.
현재 위치는  수박 입니다.
현재 위치는  사과 입니다.
현재 위치는  앵두 입니다.
현재 위치는  오렌지 입니다.
현재 위치는  수박 입니다.
현재 위치는  사과 입니다.


In [0]:
fruits.current.item

'사과'

H.W # 4: 아래는 이미지 파일을 선택해 보여주는 tkinter 프로그램이다. 이 프로그램을 수정하여 이미지 폴더를 선택하면 그 안의 모든 파일을 순환적으로 보여주는 프로그램으로 바꾸세요.

In [0]:
# 파이참 환경에서 실행할 것

from tkinter import filedialog
import tkinter as tk
from PIL import ImageTk, Image # PIL 패키지 설치 필요 > Anaconda Prompt > 'pip install image'

class Window:
    def __init__(self):
        self.window=tk.Tk()
        self.window.title("Image Viewer")
        self.window.geometry("640x480")
        self.window.resizable(False, False)

        # 메뉴바를 윈도우에 추가한다.
        menubar = tk.Menu(self.window)
        menu_1 = tk.Menu(menubar, tearoff=0)
        menu_1.bind('<<MenuSelect>>')

        menu_1.add_command(label="Open", command=self.fileSelect)
        menubar.add_cascade(label="File", menu=menu_1)

        self.window.config(menu=menubar)

        # 이미지 라벨을 추가한다.
        self.imgLabel = tk.Label(self.window, width=400, height=400, relief='solid')
        self.imgLabel.pack()

        self.window.mainloop()

    # 메뉴에서 close 가 선택되었을 때 수행한다.
    def close(self):
        self.window.quit()
        self.window.destroy()

    # 파일을 선택한다.
    
    def fileSelect(self):
        # 초기 디렉토리를 루트로 지정하고 파일을 선택하면 해당 파일명을 selFile에 입력한다.
        
        selFile = filedialog.askopenfilename(initialdir="/", title="Select file", filetypes=(("image files", "*.jpg *.png"), ("all files", "*.*")))
        print(selFile)
        self.image = Image.open(selFile)
        print(self.image.size[0], self.image.size[1])
        # 해당 이미지의 크기를 400, 400으로 resize 한다.
        if self.image.size[1] > self.image.size[0]:
            hSize = int((400 * self.image.size[0] / self.image.size[1]))
            vSize = 400
        else:
            hSize = 400
            vSize = int((400 * self.image.size[1] / self.image.size[0]))

            self.image = self.image.resize((hSize,vSize), Image.ANTIALIAS)
            self.image = ImageTk.PhotoImage(self.image)
            self.imgLabel.config(image = self.image)

a = Window()

TclError: ignored

In [0]:
# 파이참 환경에서 실행할 것

from tkinter import filedialog
import tkinter as tk
from PIL import ImageTk, Image # PIL 패키지 설치 필요 > Anaconda Prompt > 'pip install image'
import os

class Window:
    def __init__(self):
        self.window=tk.Tk()
        self.window.title("Image Viewer")
        self.window.geometry("640x480")
        self.window.resizable(False, False)

        # 메뉴바를 윈도우에 추가한다.
        menubar = tk.Menu(self.window)
        menu_1 = tk.Menu(menubar, tearoff=0)
        menu_1.bind('<<MenuSelect>>')

        menu_1.add_command(label="Open", command=self.fileSelect)
        menubar.add_cascade(label="File", menu=menu_1)

        self.window.config(menu=menubar)
        
        # 이미지 라벨을 추가한다.
        self.imgLabel = tk.Label(self.window, width=400, height=400, relief='solid')
        self.imgLabel.pack()
        


        
        self.window.mainloop()
        



    # 메뉴에서 close 가 선택되었을 때 수행한다.
    def close(self):
        self.window.quit()
        self.window.destroy()

    # 파일을 선택한다.
    
    def fileSelect(self):
        # 초기 디렉토리를 루트로 지정하고 파일을 선택하면 해당 파일명을 selFile에 입력한다.
        
        dirName=filedialog.askdirectory()
        print(dirName)
        file_list = os.listdir(dirName)
        file_directory = CircleLinkedList()
        for i in file_list:
            filename = dirName+"/"+i
            file_directory.append(filename)
        self.image = Image.open(file_directory.root.item)
        print(self.image.size[0], self.image.size[1])
        # 해당 이미지의 크기를 400, 400으로 resize 한다.
        if self.image.size[1] > self.image.size[0]:
            hSize = int((400 * self.image.size[0] / self.image.size[1]))
            vSize = 400
        else:
            hSize = 400
            vSize = int((400 * self.image.size[1] / self.image.size[0]))

            self.image = self.image.resize((hSize,vSize), Image.ANTIALIAS)
            self.image = ImageTk.PhotoImage(self.image)
            self.imgLabel.config(image = self.image)
    

        
        
a = Window()

In [0]:
# import할때의 기본 경로 설정

# 아나콘다 프롬포트 > "set PYTHONPATH = '''경로'''" 입력

In [0]:
from tkinter import filedialog
import tkinter as tk
from PIL import ImageTk, Image # PIL 패키지 설치 필요 > Anaconda Prompt > 'pip install image'
import os
import threading
#from 폴더 import 파일
# CIrcleLinkedList를 모듈로 만들어서 import를 통해 불러온다.

class Window:
    def __init__(self):
        self.window=tk.Tk()
        self.window.title("Image Viewer") # 제목
        self.window.geometry("640x480") # 창 크기
        self.window.resizable(False, False) # 창 크기 조절 불가능
        self.pngLists = """경로""" #CircleLinkedList가 들어있는 경로 설정

        # 메뉴바를 윈도우에 추가한다.
        menubar = tk.Menu(self.window)
        menu_1 = tk.Menu(menubar, tearoff=0)
        menu_1.bind('<<MenuSelect>>')

        menu_1.add_command(label="Open", command=self.dirSelect)
        menu_1.add_command(label="Close", command=self.close)
        menubar.add_cascade(label="File", menu=menu_1)

        self.window.config(menu=menubar)

        # 이미지 라벨을 추가한다.(초기화면에 이미지 라벨이 표시된 상태)
        self.imgLabel = tk.Label(self.window, width=400, height=400, relief='solid') # 이미지 라벨의 크기(불러온 이미지의 크기) 설정, solid는 이미지를 불러온 후의 테두리
        self.imgLabel.pack()

        self.window.mainloop() # 창이 켜진 후 명령 대기상태가 지속적으로 유지

    # 메뉴에서 close 가 선택되었을 때 수행한다.
    def close(self):
        self.window.quit() # 윈도우에서 종료
        self.window.destroy() # 메모리에서 종료
        
    def dirSelect(self):
        selDir = filedialog.askdirectory(initialdir = "/", title = "Select directory")
        pngfiles = [x for x in os.liistdir(selDir) if x.endswith(".png")]
        print(pngfiles)
        
        for fname in pngfiles:
          self.pngLists.append(selDir + "/" + fname)
        



    # 파일을 선택한다.
    def fileSelect(self):
        # 초기 디렉토리를 루트로 지정하고 파일을 선택하면 해당 파일명을 selFile에 입력한다.
        
        selFile = filedialog.askopenfilename(initialdir="/", title="Select file", filetypes=(("image files", "*.jpg *.png"), ("all files", "*.*")))
        print(selFile)
        self.image = Image.open(selFile)
        print(self.image.size[0], self.image.size[1])
        # 해당 이미지의 크기를 400, 400으로 resize 한다.
        if self.image.size[1] > self.image.size[0]:
            hSize = int((400 * self.image.size[0] / self.image.size[1]))
            vSize = 400
        else:
            hSize = 400
            vSize = int((400 * self.image.size[1] / self.image.size[0]))

        self.image = self.image.resize((hSize,vSize), Image.ANTIALIAS)
        self.image = ImageTk.PhotoImage(self.image)
        self.imgLabel.config(image = self.image)
        
    def next(self):
      

a = Window()